language:
  node_js
install:
  - npm install -g codecov
# safelist
branches:
  only:
  - develop
script:
  - istanbul cover --config ./istanbul.yml ./node_modules/mocha/bin/_mocha ./TEST/UNIT/ --report lcovonly -- -R spec && codecov
  - codecov
