language: node_js
node_js:
- 6.9.1
branches:
  only:
  - develop
services:
- docker
before_install:
- docker build -t bigstats/rpm-build-container ./build/
script:
- "./node_modules/istanbul/lib/cli.js cover --config ./istanbul.yml ./node_modules/mocha/bin/_mocha
  ./TEST/UNIT/ --report lcovonly -- -R spec && ./node_modules/.bin/codecov"
- docker run --rm -v $(pwd):/home/bigstats:rw bigstats/rpm-build-container /bin/sh
  -c "cd /home/bigstats;./build/buildRpm.sh;"
deploy:
  provider: releases
  api_key:
    secure: H7bnkZEb7a4upD/pA1ev1ws3kLVwk/RWw5MHebuVIv1FTLAULbztleZs+A0FMhtXUJ+oteL/Jd1148jiE6s7SZgsT+zQ80ogtiCl0g5pJpmWVgslrr5mj9rmd2aQJcZzXliryYlv9MdzvCDvBWLXnGwFfm9nEzugt+Dprn2dcbzIGxMix2yAi8g6JV3BRRGRIPCuP1z+bEWyksRnDVUKQRlE3bCqqOuv5lQAMsvVkZYVrTBvHDkec93OqKcvw7jAsSwCZglpQcSUA5BOk26jlHWyzDEyNyDbh2x/JjA+FJOJk+xmZMLOPxmJOdnqYMZ9PMgXDonaMPQ4c2938DMEhmiv2Wfa/8nb8XKSKMB+0VxJtKfJqTGoyI+OUNYJiBRgMQuXFK//Ih5ZVZUASDl9E4D9nUlewp77C3a9DYhDClPK+jB3qWdSVske8egWgR6yUqfgF1duG6XKf3mYLhY4bc1tm4qAZZCFXdh8CqSjcdvqKMkmn2/MT9ZSMkzEAMlNbxTg+ZUiml3eXoep0XTNMWLbCJ1N2yGvOPGSTixolKe6swb4UyneSnIw6T4dLC3FHiUMD3/pYSDvjen6iLkxannD+aAZ80rZ2moKgZ0MAuXDSHnR8lZSzlwLWczGncodxL0vOBc5jufEWZU9k5MBVyRK5qNhYUQFbm/+Y+TRUjY=
  file: "build/rpmbuild/RPMS/noarch/BigStats-*.noarch.rpm"
  on:
    repo: aknot242/BigStats
    branch: develop
