language: node_js
node_js:
  - "node"
install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g codecov
# safelist
branches:
  only:
  - develop
script:
  - istanbul cover --config ./istanbul.yml _mocha ./TEST/UNIT/ --report lcovonly -- -R spec && codecov
  - codecov
